### ISSUE TITLE
more about what this is?

### ISSUE THREAD

**Issue by titaniumbones** [bwinton/atom-build-markdown#2]
Hi, 

can you say more about what this is? I'm intrigued...
matt

**Comment by bwinton** [comment]
Yeah, great question!  (I really need to update the README, eh?  :)

This is a plugin for the latest version of [atom-build](https://atom.io/packages/build), which is a package that lets you run build scripts based on what files are in your project.  This plugin, in particular, will launch `Marked.app` (or `Marked 2.app` in the upcoming version) on Mac OS X if you try to build a file whose name ends in `.md` or `.mkd`.  If you use Linux or Windows, and have a favourite Markdown previewer, I would love to add support for those, too!

**Comment by bwinton** [comment]
And fixed in 323d26f09fd3e6e85758a351e7a38cd550b1f33a :wink:
