### ISSUE TITLE
Deprecated providedService 1.0.0

### ISSUE THREAD

**Issue by noseglid** [bwinton/atom-build-markdown#3]
Next version of Build will no longer support the `^1.0.0` of provided services. This has been deprecated since `v0.50.0` of the build package.

[Please see the documentation to upgrade to version ^2.0.0](https://github.com/noseglid/atom-build/blob/master/create-provider.md).

**Comment by bwinton** [comment]
Fixed in 8e4294e4780b1bbc440e174f77fd75dba9bfa9ea
Thanks!  :grinning:
